name: Deploy Website

on:
  push:
    branches:
      - test-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS with rsync
      uses: Burnett01/rsync-deployments@6.0.2 # Use a specific version
      with:
        switches: -rltgoDvz --delete # Your rsync switches
        path: ./ # Source path on runner
        remote_path: /var/www/gavinwood.net/html/ # Target path on VPS
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: 22
        exclude: | # Use multi-line for excludes
          .git/
          .github/
