name: Deploy Website

on:
  push:
    branches:
      - test-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: easing-themes/ssh-deploy@v5.0.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        SOURCE: "./" # Deploy the entire repository
        TARGET: "/var/www/gavinwood.net/html/"
        EXCLUDE: "/.git/, /.github/"
        REMOTE_PORT: "22"
        ARGS: "-rltgoDvz --delete"  # Use rsync and delete old files
